<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Y.Keb0N' shared service.

return $this->privates['.service_locator.Y.Keb0N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
], [
    'repository' => 'App\\Repository\\TransactionRepository',
    'serializer' => '?',
]);
