<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.KCPCt9Y' shared service.

return $this->privates['.service_locator.KCPCt9Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BlockController::block' => ['privates', '.service_locator.hhnBTON', 'get_ServiceLocator_HhnBTONService.php', true],
    'App\\Controller\\ListerController::listeUser' => ['privates', '.service_locator.8y.KGTd', 'get_ServiceLocator_8y_KGTdService.php', true],
    'App\\Controller\\ListerController::listeutilisateur' => ['privates', '.service_locator.ORR4EEv', 'get_ServiceLocator_ORR4EEvService.php', true],
    'App\\Controller\\ListerController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\ListesTransController::listetrans' => ['privates', '.service_locator.Y.Keb0N', 'get_ServiceLocator_Y_Keb0NService.php', true],
    'App\\Controller\\ListesTransController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\NibodjiController::argent' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\NibodjiController::nonaccess' => ['privates', '.service_locator.ZFvmlw1', 'get_ServiceLocator_ZFvmlw1Service.php', true],
    'App\\Controller\\NibodjiController::register' => ['privates', '.service_locator.wS08rY.', 'get_ServiceLocator_WS08rY_Service.php', true],
    'App\\Controller\\TransfertController::listetrans' => ['privates', '.service_locator.Y.Keb0N', 'get_ServiceLocator_Y_Keb0NService.php', true],
    'App\\Controller\\TransfertController::retrait' => ['privates', '.service_locator.xbZ0nRR', 'get_ServiceLocator_XbZ0nRRService.php', true],
    'App\\Controller\\TransfertController::transfert' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\BlockController:block' => ['privates', '.service_locator.hhnBTON', 'get_ServiceLocator_HhnBTONService.php', true],
    'App\\Controller\\ListerController:listeUser' => ['privates', '.service_locator.8y.KGTd', 'get_ServiceLocator_8y_KGTdService.php', true],
    'App\\Controller\\ListerController:listeutilisateur' => ['privates', '.service_locator.ORR4EEv', 'get_ServiceLocator_ORR4EEvService.php', true],
    'App\\Controller\\ListerController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\ListesTransController:listetrans' => ['privates', '.service_locator.Y.Keb0N', 'get_ServiceLocator_Y_Keb0NService.php', true],
    'App\\Controller\\ListesTransController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\NibodjiController:argent' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\NibodjiController:nonaccess' => ['privates', '.service_locator.ZFvmlw1', 'get_ServiceLocator_ZFvmlw1Service.php', true],
    'App\\Controller\\NibodjiController:register' => ['privates', '.service_locator.wS08rY.', 'get_ServiceLocator_WS08rY_Service.php', true],
    'App\\Controller\\TransfertController:listetrans' => ['privates', '.service_locator.Y.Keb0N', 'get_ServiceLocator_Y_Keb0NService.php', true],
    'App\\Controller\\TransfertController:retrait' => ['privates', '.service_locator.xbZ0nRR', 'get_ServiceLocator_XbZ0nRRService.php', true],
    'App\\Controller\\TransfertController:transfert' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
], [
    'App\\Controller\\BlockController::block' => '?',
    'App\\Controller\\ListerController::listeUser' => '?',
    'App\\Controller\\ListerController::listeutilisateur' => '?',
    'App\\Controller\\ListerController::setViewHandler' => '?',
    'App\\Controller\\ListesTransController::listetrans' => '?',
    'App\\Controller\\ListesTransController::setViewHandler' => '?',
    'App\\Controller\\NibodjiController::argent' => '?',
    'App\\Controller\\NibodjiController::nonaccess' => '?',
    'App\\Controller\\NibodjiController::register' => '?',
    'App\\Controller\\TransfertController::listetrans' => '?',
    'App\\Controller\\TransfertController::retrait' => '?',
    'App\\Controller\\TransfertController::transfert' => '?',
    'App\\Controller\\BlockController:block' => '?',
    'App\\Controller\\ListerController:listeUser' => '?',
    'App\\Controller\\ListerController:listeutilisateur' => '?',
    'App\\Controller\\ListerController:setViewHandler' => '?',
    'App\\Controller\\ListesTransController:listetrans' => '?',
    'App\\Controller\\ListesTransController:setViewHandler' => '?',
    'App\\Controller\\NibodjiController:argent' => '?',
    'App\\Controller\\NibodjiController:nonaccess' => '?',
    'App\\Controller\\NibodjiController:register' => '?',
    'App\\Controller\\TransfertController:listetrans' => '?',
    'App\\Controller\\TransfertController:retrait' => '?',
    'App\\Controller\\TransfertController:transfert' => '?',
]);
