<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJWsaYzS\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJWsaYzS/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJWsaYzS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJWsaYzS\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJWsaYzS\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'JWsaYzS',
    'container.build_id' => '3c8124b1',
    'container.build_time' => 1567827501,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJWsaYzS');
